[package]
name = "lust"
version = "0.1.0"
authors = ["Sean Prashad <S.Prashad@outlook.com>"]
description = "A Rust library intended for finding out everything about your beloved file system"
repository = "https://github.com/SeanPrashad/Lust"
readme = "README.md"
license = "MIT"

[dependencies]
rust-crypto = "^0.2"

[features]
default = []
