[package]
name = "lust"
version = "0.1.0"
authors = ["Sean Prashad <S.Prashad@outlook.com>"]
description = "A Rust library intended for finding out everything about your beloved file system"
repository = "https://github.com/SeanPrashad/Lust"
readme = "README.md"
license = "MIT"

[dependencies]
sha1 = "0.2.0"
md5 = "0.3.6"
clippy = {version = "*", optional = true}

[features]
default = []